# Tipos de Estrutura em Python

listas, tuplas, conjuntos, dicionário e matriz.

São usados para armazenar mais de um valor, também chamados de estruturas de dados.


Objetos do tipo sequência: texto, listas e tuplas.

Objetos do tipo set (conjunto).

Objetos do tipo mapping (dicionário).

Objetos do tipo array NumPy


# 1 - Objetos do tipo sequência: texto, listas e tuplas.

Os objetos do tipo sequência são estruturas de dados capazes de armazenar mais de um valor. Essas estruturas de dados representam sequências finitas indexadas por números não negativos. O primeiro elemento de uma sequência ocupa o índice 0; o segundo, 1; o último elemento, a posição n - 1, em que n é capacidade de armazenamento da sequência.

**TEXTOS**


In [1]:
texto = "Aprendendo Python na disciplina de linguagem de programação."

print(f"Tamanho do texto = {len(texto)}") #o len permite saber o tamanho da sequência
print(f"Python in texto = {'Python' in texto}") #O operador 'in', por sua vez, permite saber se um determinado valor está ou não na sequência
print(f"Quantidade de y no texto = {texto.count('y')}") #count permite contar a quantidade de ocorrências de um valor
print(f"As 5 primeiras letras são: {texto[0:6]}") #E a notação com colchetes permite fatiar a sequência, exibindo somente partes dela

Tamanho do texto = 60
Python in texto = True
Quantidade de y no texto = 1
As 5 primeiras letras são: Aprend


In [26]:
texto = "Aprendendo Python na disciplina de linguagem de programação."

print(texto.upper())
print(texto.replace("i", 'XX'))

APRENDENDO PYTHON NA DISCIPLINA DE LINGUAGEM DE PROGRAMAÇÃO.
Aprendendo Python na dXXscXXplXXna de lXXnguagem de programação.


In [9]:
texto = "Aprendendo Python na disciplina de linguagem de programação."

print(f"Texto: {texto}")
print(f"Texto: {len(texto)}\n")
      
palavras = texto.split()
print(f"Texto: {palavras}")
print(f"Texto: {len(palavras)}")


Texto: Aprendendo Python na disciplina de linguagem de programação.
Texto: 60

Texto: ['Aprendendo', 'Python', 'na', 'disciplina', 'de', 'linguagem', 'de', 'programação.']
Texto: 8


In [30]:
texto = """Operadores de String
Python oferece operadores para processar texto (ou seja, valores de string).
Assim como os números, as strings podem ser comparadas usando operadores de comparação:
==, !=, <, > e assim por diante.
O operador ==, por exemplo, retorna True se as strings nos dois lados do operador tiverem o mesmo valor (Perkovic, p. 23, 2016).
"""
print(f"Tamanho do texto: {len(texto)}\n")
texto = texto.lower()
lista_palavras = texto.split()
print(texto)
valString = texto.count('string')
valStrings = texto.count('strings')

print(f"Tamanho da lista de palavras: {len(lista_palavras)}")
print(f"Quantidade de strings: {texto.count('string')}")
print(f"Quantidade de string: {texto.count('strings')}")
print(f"Total de palavras 'string' e 'strings': {valString + valStrings}")

Tamanho do texto: 348

operadores de string
python oferece operadores para processar texto (ou seja, valores de string).
assim como os números, as strings podem ser comparadas usando operadores de comparação:
==, !=, <, > e assim por diante.
o operador ==, por exemplo, retorna true se as strings nos dois lados do operador tiverem o mesmo valor (perkovic, p. 23, 2016).

Tamanho da lista de palavras: 58
Quantidade de strings: 4
Quantidade de string: 2
Total de palavras 'string' e 'strings': 6


**LISTAS**

Lista é uma estrutura de dados do tipo sequencial que possui como principal característica ser mutável. Ou seja, novos valores podem ser adicionados ou removidos da sequência. Os objetos do tipo sequência são indexados, o que significa que cada elemento ocupa uma posição que começa em 0

**enumerate()**, é usada para percorrer um objeto iterável retornando a posição e o valor

In [34]:
vogais = ['a', 'e', 'i', 'o', 'u']

for vogal in vogais:
    print(f'Posição da vogal {vogal} na lista: {vogais.index(vogal)}')
    

Posição da vogal a na lista: 0
Posição da vogal e na lista: 1
Posição da vogal i na lista: 2
Posição da vogal o na lista: 3
Posição da vogal u na lista: 4


In [52]:
#Mesma coisa de modo diferente
vogais = []
print(f'Tipo da variável vogais: {type(vogais)}')

vogais.append('a')
vogais.append('e')
vogais.append('i')
vogais.append('o')
vogais.append('u')

for vogal in vogais:
    print(f'Posição da vogal {vogal}: {vogais.index(vogal)}')
    
print(f"\n{vogais[1:5]}")

print("\n")

#ou

for index_vogal, volga in enumerate(vogais):
    print(f"Posição da vogal {volga}: {index_vogal}")

Tipo da variável vogais: <class 'list'>
Posição da vogal a: 0
Posição da vogal e: 1
Posição da vogal i: 2
Posição da vogal o: 3
Posição da vogal u: 4

['e', 'i', 'o', 'u']


Posição da vogal a: 0
Posição da vogal e: 1
Posição da vogal i: 2
Posição da vogal o: 3
Posição da vogal u: 4


In [13]:
frutas = ['Maçã', 'Banana', 'Uva', 'Melancia', 'Goiaba', 'Maçã']
notas = [8.7, 9.0, 9.1, 4.5, 7.8]

print('Maçã' in frutas)
print('Limão' in frutas)
print('Banana' in frutas)
print('Pera' not in frutas)
print(frutas.count('Maçã'))
print(min(frutas)) #O mínimo de uma lista de palavras é feito sobre a ordem alfabética.
print(min(notas))
print(frutas + notas)
print(2 * frutas)
print(2 * notas)

True
False
True
True
2
Banana
4.5
['Maçã', 'Banana', 'Uva', 'Melancia', 'Goiaba', 'Maçã', 8.7, 9.0, 9.1, 4.5, 7.8]
['Maçã', 'Banana', 'Uva', 'Melancia', 'Goiaba', 'Maçã', 'Maçã', 'Banana', 'Uva', 'Melancia', 'Goiaba', 'Maçã']
[8.7, 9.0, 9.1, 4.5, 7.8, 8.7, 9.0, 9.1, 4.5, 7.8]


In [31]:
lista = ['Python', 30.61, "Java", 51 , ['a', 'b', 20], "maça"]

print("Tamaho da lista: ", len(lista))

for i, item in enumerate(lista):
    print(f"Posição: {i}; Item: {item}; Tipo do item: {type(item)}")
    
#ou
print("\n")

for item in lista:
    print(f"Posição: {lista.index(item)}; Item: {item}; Tipo do item: {type(item)}")

print("\n")

print("lista[1] = ", lista[1])
print("lista[0:2] = ", lista[0:2])
print("lista[:2] = ", lista[:2])
print("lista[3:5] = ", lista[3:5])
print("lista[3:6] = ", lista[3:6])
print("lista[3:] = ", lista[3:])
print("lista[-2] = ", lista[-2])
print("lista[-1] = ", lista[-1])
print("lista[4][1] = ", lista[4][1])


Tamaho da lista:  6
Posição: 0; Item: Python; Tipo do item: <class 'str'>
Posição: 1; Item: 30.61; Tipo do item: <class 'float'>
Posição: 2; Item: Java; Tipo do item: <class 'str'>
Posição: 3; Item: 51; Tipo do item: <class 'int'>
Posição: 4; Item: ['a', 'b', 20]; Tipo do item: <class 'list'>
Posição: 5; Item: maça; Tipo do item: <class 'str'>


Posição: 0; Item: Python; Tipo do item: <class 'str'>
Posição: 1; Item: 30.61; Tipo do item: <class 'float'>
Posição: 2; Item: Java; Tipo do item: <class 'str'>
Posição: 3; Item: 51; Tipo do item: <class 'int'>
Posição: 4; Item: ['a', 'b', 20]; Tipo do item: <class 'list'>
Posição: 5; Item: maça; Tipo do item: <class 'str'>


lista[1] =  30.61
lista[0:2] =  ['Python', 30.61]
lista[:2] =  ['Python', 30.61]
lista[3:5] =  [51, ['a', 'b', 20]]
lista[3:6] =  [51, ['a', 'b', 20], 'maça']
lista[3:] =  [51, ['a', 'b', 20], 'maça']
lista[-2] =  ['a', 'b', 20]
lista[-1] =  maça
lista[4][1] =  b


**LIST COMPREHENSION (COMPREENSÕES DE LISTA/LISTCOMP)**

A list comprehension, também chamada de listcomp, é uma forma pythônica de criar uma lista com base em um objeto iterável.  Esse tipo de técnica é utilizada quando, dada uma sequência, deseja-se criar uma nova sequência, porém com as informações originais transformadas ou filtradas por um critério

In [44]:
linguagens = ["Python", "Java", "JavaScript", "C", "C#", "C++", "Swift", "Go", "Kotlin"]

print("Lista antes da iteração: ", linguagens)

linguagens = [item.lower() for item in linguagens]

print("Lista depois da iteração: ", linguagens)

Lista antes da iteração:  ['Python', 'Java', 'JavaScript', 'C', 'C#', 'C++', 'Swift', 'Go', 'Kotlin']
Lista depois da iteração:  ['python', 'java', 'javascript', 'c', 'c#', 'c++', 'swift', 'go', 'kotlin']


In [51]:
linguagens = '''Python Java JavaScript C C# C++ Swift Go Kotlin'''
linguagens = linguagens.split()
print(linguagens)

linguagens_java = [item for item in linguagens if 'Java' in item] #se houver 'Java' no item
print(linguagens_java)

['Python', 'Java', 'JavaScript', 'C', 'C#', 'C++', 'Swift', 'Go', 'Kotlin']
['Java', 'JavaScript']


FUNÇÕES MAP()

A função map() é utilizada para aplicar uma determinada função em cada item de um objeto iterável. A função map() exige que sejam passados dois parâmetros: a função e o objeto iterável

In [58]:
linguagens = '''Python Java JavaScript C C# C++ Swift Go Kotlin'''.split()

nova_lista = list(map(lambda x: x.lower(), linguagens))
# O list() transforma o objeto em uma lista
print(nova_lista)

['python', 'java', 'javascript', 'c', 'c#', 'c++', 'swift', 'go', 'kotlin']


In [60]:
numero = [1, 2, 3, 4, 5]

print("Lista antiga: ", numero)
numero = list(map(lambda x: x + 1, numero))
print("Lista nova: ", numero)

Lista antiga:  [1, 2, 3, 4, 5]
Lista nova:  [2, 3, 4, 5, 6]


FUNÇÃO FILTER()

A função filter() tem as mesmas características da função map(), mas, em vez de usarmos uma função para transformar os valores da lista, nós a usamos para filtrar.

In [69]:
numero = list(range(0, 21)) #assim mostra os valores do range
#Objetos iteráveis precisam do list() para mostrar os valores
print(type(numero))
numero = list(filter(lambda x: x%2 == 0, numero))#filtrando
numero

<class 'list'>


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

**TUPLAS**

A grande diferença entre listas e tuplas é que as primeiras são mutáveis, razão pela qual, com elas, conseguimos fazer atribuições a posições específicas: por exemplo, lista[2] = 'maça'. Por sua vez, nas tuplas isso não é possível, uma vez que são objetos imutáveis.

Como a tupla é imutável, sua utilização ocorre em casos nos quais a ordem dos elementos é importante e não pode ser alterada, já que o objeto tuple garante essa característica.

In [70]:
a = ('a', 'b', 'c', 'd')
print(a)
print(type(a))

('a', 'b', 'c', 'd')
<class 'tuple'>


# 2 - Objetos do tipo set (conjunto).

Um objeto do tipo set habilita operações matemáticas de conjuntos, tais como: união, intersecção, diferenteça, etc. Esse tipo de estrutura pode ser usado, portanto, em testes de associação e remoção de valores duplicados de uma sequência

In [1]:
vogais_1 = {'aeiou'} # sem uso do construtor
print(type(vogais_1), vogais_1)

vogais_2 = set('aeiouaaaaaa') # construtor com string
print(type(vogais_2), vogais_2)

vogais_3 = set(['a', 'e', 'i', 'o', 'u']) # construtor com lista
print(type(vogais_3), vogais_3)

vogais_4 = set(('a', 'e', 'i', 'o', 'u')) # construtor com tupla
print(type(vogais_4), vogais_4)

print(set('banana'))

<class 'set'> {'aeiou'}
<class 'set'> {'u', 'i', 'a', 'e', 'o'}
<class 'set'> {'u', 'i', 'a', 'e', 'o'}
<class 'set'> {'u', 'i', 'a', 'e', 'o'}
{'b', 'n', 'a'}


In [4]:
def create_report():
    componentes_verificados = set(['caixas de som', 'cooler', 'dissipador de calor', 'cpu', 'hd', 'estabilizador', 'gabinete', 'hub', 'impressora', 'joystick', 'memória ram', 'microfone', 'modem', 'monitor', 'mouse', 'no-break', 'placa de captura', 'placa de som', 'placa de vídeo', 'placa mãe', 'scanner', 'teclado', 'webcam'])
    componentes_com_defeito = set(['hd', 'monitor', 'placa de som', 'scanner'])
    
    qtde_componentes_verificados = len(componentes_verificados)
    qtde_componentes_com_defeito = len(componentes_com_defeito)
    
    componentes_ok = componentes_verificados.difference(componentes_com_defeito)
    
    print(f"Foram verificados {qtde_componentes_verificados} componentes.\n")
    print(f"{qtde_componentes_com_defeito} componentes apresentaram defeito.\n")
    
    print("Os componentes que podem ser vendidos são:")
    for item in componentes_ok:
        print(item)


create_report()

Foram verificados 23 componentes.

4 componentes apresentaram defeito.

Os componentes que podem ser vendidos são:
joystick
modem
placa de vídeo
mouse
estabilizador
hub
no-break
dissipador de calor
gabinete
webcam
impressora
microfone
cooler
placa mãe
caixas de som
placa de captura
memória ram
cpu
teclado


In [17]:
def verifica_pagadores():
    quem_comprou = set(['José', 'Gabriel', 'João', 'Pedro', 'Laura', 'Vincius', 'Bárbara', 'Ana', 'Felipe', 'Gustavo', 'Maria'])
    quem_me_deve = set(['José', 'Laura', 'Gustavo'])
    lista_devedor = []
    
    quem_pagou = quem_comprou.difference(quem_me_deve) #aqui faz a interseção
    
    #porcentagem de quem ainde me deve
    tamanho_quem_comprou = len(quem_comprou)
    tamanho_quem_me_deve = len(quem_me_deve)
    
    falta_pagar_porcentagem = tamanho_quem_comprou / tamanho_quem_me_deve
    
    print("Quem me deve: \n")
    for deve in quem_me_deve:
        lista_devedor.append(deve)
    
    print(lista_devedor)    
    
    print("Os que pagaram foram: \n")
    for pagaram in quem_pagou:
        print(pagaram)
    
    print("Quantos % ainda faltam para me pagar: ", falta_pagar_porcentagem)

verifica_pagadores()

Quem me deve: 

['Gustavo', 'Laura', 'José']
Os que pagaram foram: 

Maria
Vincius
Bárbara
Gabriel
Pedro
Ana
João
Felipe
Quantos % ainda faltam para me pagar:  3.6666666666666665


# 3 - OBJETOS DO TIPO MAPPING

As estruturas de dados que possuem um mapeamento entre uma chave e um valor são consideradas objetos do tipo mapping. Em Python, o objeto que possui essa propriedade é o dict (dicionário). Uma vez que esse objeto é mutável,  conseguimos atribuir um novo valor a uma chave já existente.


In [18]:
# Exemplo 1 - Criação de dicionário vazio, com atribuição posterior de chave e valor 
dici_1 = {}
dici_1['nome'] = "João"
dici_1['idade'] = 30

# Exemplo 2 - Criação de dicionário usando um par elementos na forma, chave : valor
dici_2 = {'nome': 'João', 'idade': 30}

# Exemplo 3 - Criação de dicionário com uma lista de tuplas. Cada tupla representa um par chave : valor
dici_3 = dict([('nome', "João"), ('idade', 30)])

# Exemplo 4 - Criação de dicionário com a função built-in zip() e duas listas, uma com as chaves, outra com os valores.
dici_4 = dict(zip(['nome', 'idade'], ["João", 30]))
#zip() é usada para combinar valores de diferentes sequências e retorna um iterável de tuplas, 
#em que o primeiro elemento é referente ao primeiro elemento da sequência 1, e assim por diante

print(dici_1 == dici_2 == dici_3 == dici_4) # Testando se as diferentes construções resultamo em objetos iguais.

True


In [19]:
cadastro = {
            'nome' : ['João', 'Ana', 'Pedro', 'Marcela'],
            'cidade' : ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba'],
            'idade' : [25, 33, 37, 18]
            }

print("len(cadastro) = ", len(cadastro))

print("\n cadastro.keys() = \n", cadastro.keys()) #Retorna uma lista com todas as chaves no dicionário.
print("\n cadastro.values() = \n", cadastro.values())#Retorna uma lista com os valores. Como os valores também são listas, temos uma lista de listas.
print("\n cadastro.items() = \n", cadastro.items())#Retorna uma lista de tuplas, cada uma das quais é composta pela chave e pelo valor.

print("\n cadastro['nome'] = ", cadastro['nome'])
print("\n cadastro['nome'][2] = ", cadastro['nome'][2])
print("\n cadastro['idade'][2:] = ", cadastro['idade'][2:])


len(cadastro) =  3

 cadastro.keys() = 
 dict_keys(['nome', 'cidade', 'idade'])

 cadastro.values() = 
 dict_values([['João', 'Ana', 'Pedro', 'Marcela'], ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba'], [25, 33, 37, 18]])

 cadastro.items() = 
 dict_items([('nome', ['João', 'Ana', 'Pedro', 'Marcela']), ('cidade', ['São Paulo', 'São Paulo', 'Rio de Janeiro', 'Curitiba']), ('idade', [25, 33, 37, 18])])

 cadastro['nome'] =  ['João', 'Ana', 'Pedro', 'Marcela']

 cadastro['nome'][2] =  Pedro

 cadastro['idade'][2:] =  [37, 18]


In [27]:
#Descobrir qual a quantidade de itens que há na chave
print(len(cadastro['nome']))
print(len(cadastro['cidade']))
print(len(cadastro['idade']))

print(len(cadastro['nome']) + len(cadastro['cidade']) + len(cadastro['idade']))

#ou
#Para cada chave, uso a função len(), criando assim uma lista de valores inteiros
qnt_valores = sum([len(cadastro[chave]) for chave in cadastro])
print(qnt_valores)


4
4
4
12
12


# 4 - OBJETOS DO TIPO ARRAY NUMPY

A biblioteca NumPy, foi criada especificamente para a computação científica com Python. NumPy é a biblioteca mais poderosa para trabalhar com dados tabulares (matrizes), além de ser um recurso essencial para os desenvolvedores científicos, como os que desenvolvem soluções de inteligência artificial para imagens.

In [28]:
import numpy
#Ou import numpy as np

matriz_1_1 = numpy.array([1, 2, 3]) # Cria matriz 1 linha e 1 coluna
matriz_2_2 = numpy.array([[1, 2], [3, 4]]) # Cria matriz 2 linhas e 2 colunas
matriz_3_2 = numpy.array([[1, 2], [3, 4], [5, 6]]) # Cria matriz 3 linhas e 2 colunas
matriz_2_3 = numpy.array([[1, 2, 3], [4, 5, 6]]) # Cria matriz 2 linhas e 3 colunas

print(type(matriz_1_1))

print('\n matriz_1_1 = ', matriz_1_1)
print('\n matriz_2_2 = \n', matriz_2_2)
print('\n matriz_3_2 = \n', matriz_3_2)
print('\n matriz_2_3 = \n', matriz_2_3)

<class 'numpy.ndarray'>

 matriz_1_1 =  [1 2 3]

 matriz_2_2 = 
 [[1 2]
 [3 4]]

 matriz_3_2 = 
 [[1 2]
 [3 4]
 [5 6]]

 matriz_2_3 = 
 [[1 2 3]
 [4 5 6]]


In [33]:
m1 = numpy.zeros((3, 3)) # Cria matriz 3 x 3 somente com zero
m2 = numpy.ones((2,2)) # Cria matriz 2 x 2 somente com um
m3 = numpy.eye(4) # Cria matriz 4 x 4 identidade
m4 = numpy.random.randint(low=0, high=100, size=10).reshape(2, 5) # A função reshape() cria matriz 2 X 5 com números inteiros

print('\n numpy.zeros((3, 3)) = \n', numpy.zeros((3, 3)))
print('\n numpy.ones((2,2)) = \n', numpy.ones((2,2)))
print('\n numpy.eye(4) = \n', numpy.eye(4))
print('\n m4 = \n', m4)

print(f"Soma dos valores em m4 = {m4.sum()}")
print(f"Valor mínimo em m4 = {m4.min()}")
print(f"Valor máximo em m4 = {m4.max()}")
print(f"Média dos valores em m4 = {m4.mean()}")


 numpy.zeros((3, 3)) = 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 numpy.ones((2,2)) = 
 [[1. 1.]
 [1. 1.]]

 numpy.eye(4) = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 m4 = 
 [[42 81 80 67 13]
 [65  2 25 92 79]]
Soma dos valores em m4 = 546
Valor mínimo em m4 = 2
Valor máximo em m4 = 92
Média dos valores em m4 = 54.6


In [54]:
m1 = numpy.zeros((3, 3))
m2 = numpy.ones((3, 3))
m3 = numpy.eye(5)
m4 = numpy.random.randint(low = 0, high = 100, size = 10).reshape(2, 5)
print("\n", m1)
print("\n", m2)
print("\n", m3)
print("\n", m4)
print("\n", m4.min())
print("\n", m4.max())
print("\n", m4.sum())
print("\n", m4.mean())


 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

 [[56 53 77 31 42]
 [41  6 95 43  0]]

 0

 95

 444

 44.4
